<template><AdminLayout><div class="container mx-auto px-2 md:px-6 py-6">
<div class="flex flex-col md:flex-row md:justify-between gap-3 mb-6"><div><h1 class="text-3xl font-medium text-gray-700">Sedes</h1><p class="text-sm text-gray-500">Ubicaciones comerciales y operativas</p></div><button @click="open()" class="bg-blue-600 text-white px-4 py-2 rounded-lg"><i class="pi pi-plus mr-2"/>Nueva sede</button></div>
<div class="bg-white rounded-lg shadow p-4 mb-4"><input v-model="search" @input="load" placeholder="Buscar por código o nombre" class="w-full md:w-96 border rounded px-3 py-2"></div>
<div class="bg-white rounded-lg shadow overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-100 text-gray-600"><tr><th class="p-3 text-left">Código</th><th class="p-3 text-left">Sede</th><th class="p-3">Almacenes</th><th class="p-3">Estado</th><th class="p-3">Acciones</th></tr></thead><tbody><tr v-for="item in items" :key="item.id" class="border-t"><td class="p-3 font-mono">{{item.code}}</td><td class="p-3"><b>{{item.name}}</b><div class="text-gray-500">{{item.address}}</div></td><td class="p-3 text-center">{{item.warehouses_count}}</td><td class="p-3 text-center"><span :class="item.is_active?'bg-green-100 text-green-700':'bg-gray-200 text-gray-600'" class="px-2 py-1 rounded-full">{{item.is_active?'Activa':'Inactiva'}}</span></td><td class="p-3 text-center"><button @click="open(item)" class="text-blue-600 mr-3"><i class="pi pi-pencil"/></button><button @click="toggle(item)" :class="item.is_active?'text-red-600':'text-green-600'"><i :class="item.is_active?'pi pi-ban':'pi pi-check-circle'"/></button></td></tr><tr v-if="!loading&&!items.length"><td colspan="5" class="p-8 text-center text-gray-500">No se encontraron sedes.</td></tr></tbody></table></div>
<div v-if="modal" class="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4"><form @submit.prevent="save" class="bg-white rounded-lg shadow-xl w-full max-w-2xl p-6"><h2 class="text-xl font-bold mb-4">{{form.id?'Editar':'Nueva'}} sede</h2><div class="grid md:grid-cols-2 gap-4"><label>Código<input v-model="form.code" required class="block w-full border rounded p-2 mt-1"></label><label>Nombre<input v-model="form.name" required class="block w-full border rounded p-2 mt-1"></label><label class="md:col-span-2">Dirección<input v-model="form.address" required class="block w-full border rounded p-2 mt-1"></label><label>Distrito<input v-model="form.district" class="block w-full border rounded p-2 mt-1"></label><label>Provincia<input v-model="form.province" class="block w-full border rounded p-2 mt-1"></label><label>Departamento<input v-model="form.department" class="block w-full border rounded p-2 mt-1"></label><label>Email<input v-model="form.email" type="email" class="block w-full border rounded p-2 mt-1"></label><label class="md:col-span-2">Descripción<textarea v-model="form.description" class="block w-full border rounded p-2 mt-1"/></label></div><div class="flex justify-end gap-3 mt-5"><button type="button" @click="modal=false" class="px-4 py-2 bg-gray-200 rounded">Cancelar</button><button :disabled="saving" class="px-4 py-2 bg-blue-600 text-white rounded">{{saving?'Guardando...':'Guardar'}}</button></div></form></div>
</div></AdminLayout></template>
<script setup>import AdminLayout from '@/layouts/AdminLayout.vue';import api from '@/api';import {ref,onMounted} from 'vue';import {useToast} from 'primevue/usetoast';import {useConfirm} from 'primevue/useconfirm';
const toast=useToast(),confirm=useConfirm(),items=ref([]),search=ref(''),loading=ref(false),modal=ref(false),saving=ref(false),form=ref({});let timer;
const load=()=>{clearTimeout(timer);timer=setTimeout(async()=>{loading.value=true;try{items.value=(await api.get('/admin/branches',{params:{search:search.value}})).data.data}catch(e){toast.add({severity:'error',summary:'Error',detail:e.response?.data?.message||'No se pudieron cargar las sedes',life:4000})}finally{loading.value=false}},200)};
const open=(x=null)=>{form.value=x?{...x}:{code:'',name:'',address:'',district:'',province:'',department:'',email:'',description:'',is_active:true};modal.value=true};
const save=async()=>{saving.value=true;try{form.value.id?await api.put(`/admin/branches/${form.value.id}`,form.value):await api.post('/admin/branches',form.value);modal.value=false;toast.add({severity:'success',summary:'Sede guardada',life:2500});load()}catch(e){toast.add({severity:'error',summary:'No se pudo guardar',detail:e.response?.data?.message||Object.values(e.response?.data?.errors||{})[0]?.[0],life:5000})}finally{saving.value=false}};
const toggle=x=>confirm.require({message:`¿${x.is_active?'Desactivar':'Activar'} la sede ${x.name}?`,header:'Confirmar',accept:async()=>{try{await api.patch(`/admin/branches/${x.id}/status`,{is_active:!x.is_active});load()}catch(e){toast.add({severity:'warn',summary:'Operación rechazada',detail:e.response?.data?.message,life:5000})}}});onMounted(load);</script>
