<template>
    <AdminLayout>
        <div class="mx-auto max-w-7xl space-y-5">
            <header class="flex flex-col gap-3 rounded-2xl bg-slate-900 p-6 text-white md:flex-row md:items-end md:justify-between">
                <div><p class="text-xs font-bold uppercase tracking-widest text-blue-300">Administración · Consultas</p><h1 class="text-3xl font-black">Reportes gerenciales</h1><p class="mt-1 text-sm text-slate-300">Consulta y exporta información operativa sin exponer datos personales.</p></div>
                <div class="text-sm text-slate-300">Generado: {{ generatedAt }}</div>
            </header>

            <section class="rounded-2xl bg-white p-4 shadow-sm" aria-label="Filtros del reporte">
                <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
                    <label class="text-sm font-semibold">Periodo<select v-model="filters.period" class="field mt-1" @change="apply"><option value="this_year">Este año</option><option value="today">Hoy</option><option value="last_7_days">Últimos 7 días</option><option value="last_30_days">Últimos 30 días</option><option value="this_month">Este mes</option><option value="previous_month">Mes anterior</option><option value="custom">Personalizado</option></select></label>
                    <label v-if="filters.period === 'custom'" class="text-sm font-semibold">Desde<input v-model="filters.date_from" type="date" class="field mt-1" @change="apply"></label>
                    <label v-if="filters.period === 'custom'" class="text-sm font-semibold">Hasta<input v-model="filters.date_to" type="date" class="field mt-1" @change="apply"></label>
                    <label v-if="activeSection === 'catalogs'" class="text-sm font-semibold">Catálogo<select v-model="filters.catalog" class="field mt-1" @change="catalogChanged"><option v-for="item in catalogOptions" :key="item.key" :value="item.key">{{ item.label }}</option></select></label>
                    <label v-if="show('delivery_type')" class="text-sm font-semibold">Modalidad<select v-model="filters.delivery_type" class="field mt-1" @change="apply"><option value="">Todas</option><option value="delivery">Delivery</option><option value="pickup">Pickup</option></select></label>
                    <label v-if="show('category_id')" class="text-sm font-semibold">Categoría<select v-model="filters.category_id" class="field mt-1" @change="apply"><option value="">Todas</option><option v-for="item in options.categories" :key="item.id" :value="item.id">{{ item.name }}</option></select></label>
                    <label v-if="show('brand_id')" class="text-sm font-semibold">Marca<select v-model="filters.brand_id" class="field mt-1" @change="apply"><option value="">Todas</option><option v-for="item in options.brands" :key="item.id" :value="item.id">{{ item.name }}</option></select></label>
                    <label v-if="show('warehouse_id')" class="text-sm font-semibold">Almacén<select v-model="filters.warehouse_id" class="field mt-1" @change="apply"><option value="">Todos</option><option v-for="item in options.warehouses" :key="item.id" :value="item.id">{{ item.name }}</option></select></label>
                    <label v-if="show('product_id')" class="text-sm font-semibold">Producto<select v-model="filters.product_id" class="field mt-1" @change="apply"><option value="">Todos</option><option v-for="item in options.products" :key="item.id" :value="item.id">{{ item.name }}</option></select></label>
                    <label v-if="show('payment_method')" class="text-sm font-semibold">Pago<select v-model="filters.payment_method" class="field mt-1" @change="apply"><option value="">Todos</option><option value="card">Tarjeta</option><option value="transfer">Transferencia</option><option value="cash_on_delivery">Contraentrega</option><option value="cash_on_pickup">Pago al recoger</option></select></label>
                    <label v-if="show('movement_type')" class="text-sm font-semibold">Tipo<select v-model="filters.movement_type" class="field mt-1" @change="apply"><option value="">Todos</option><option v-for="item in movementTypes" :key="item" :value="item">{{ item }}</option></select></label>
                    <label v-if="show('movement_direction')" class="text-sm font-semibold">Dirección<select v-model="filters.movement_direction" class="field mt-1" @change="apply"><option value="">Todas</option><option value="in">Entrada</option><option value="out">Salida</option><option value="neutral">Neutro</option></select></label>
                    <label v-if="show('severity')" class="text-sm font-semibold">Severidad<select v-model="filters.severity" class="field mt-1" @change="apply"><option value="">Todas</option><option v-for="item in severities" :key="item" :value="item">{{ item }}</option></select></label>
                    <label v-if="show('overdue')" class="text-sm font-semibold">Vencido<select v-model="filters.overdue" class="field mt-1" @change="apply"><option value="">Todos</option><option value="1">Sí</option><option value="0">No</option></select></label>
                    <label v-if="show('reason_code')" class="text-sm font-semibold">Razón<select v-model="filters.reason_code" class="field mt-1" @change="apply"><option value="">Todas</option><option v-for="item in reasonCodes" :key="item" :value="item">{{ item }}</option></select></label>
                    <label v-if="show('stage')" class="text-sm font-semibold">Etapa<select v-model="filters.stage" class="field mt-1" @change="apply"><option value="">Todas</option><option v-for="item in stages" :key="item" :value="item">{{ item }}</option></select></label>
                    <label v-if="show('metric')" class="text-sm font-semibold">Métrica<select v-model="filters.metric" class="field mt-1" @change="apply"><option value="">Todas</option><option v-for="item in metrics" :key="item" :value="item">{{ item }}</option></select></label>
                    <label v-if="show('search')" class="text-sm font-semibold">Buscar<input v-model="filters.search" class="field mt-1" placeholder="Buscar…" @keyup.enter="apply"></label>
                    <label v-if="show('is_active')" class="text-sm font-semibold">Estado<select v-model="filters.is_active" class="field mt-1" @change="apply"><option value="">Todos</option><option value="1">Activos</option><option value="0">Inactivos</option></select></label>
                    <label v-if="catalogSupports('branch_id')" class="text-sm font-semibold">Sede<select v-model="filters.branch_id" class="field mt-1" @change="apply"><option value="">Todas</option><option v-for="item in options.branches" :key="item.id" :value="item.id">{{ item.name }}</option></select></label>
                    <label v-if="catalogSupports('department_id')" class="text-sm font-semibold">Departamento<select v-model="filters.department_id" class="field mt-1" @change="apply"><option value="">Todos</option><option v-for="item in options.departments" :key="item.id" :value="item.id">{{ item.name }}</option></select></label>
                    <label v-if="catalogSupports('province_id')" class="text-sm font-semibold">Provincia<select v-model="filters.province_id" class="field mt-1" @change="apply"><option value="">Todas</option><option v-for="item in options.provinces" :key="item.id" :value="item.id">{{ item.name }}</option></select></label>
                    <label v-if="catalogSupports('zone_id')" class="text-sm font-semibold">Zona<select v-model="filters.zone_id" class="field mt-1" @change="apply"><option value="">Todas</option><option v-for="item in options.zones" :key="item.id" :value="item.id">{{ item.name }}</option></select></label>
                    <label v-if="catalogSupports('district_id')" class="text-sm font-semibold">Distrito<select v-model="filters.district_id" class="field mt-1" @change="apply"><option value="">Todos</option><option v-for="item in options.districts" :key="item.id" :value="item.id">{{ item.name }}</option></select></label>
                    <label v-if="catalogSupports('allows_pickup')" class="text-sm font-semibold">Pickup<select v-model="filters.allows_pickup" class="field mt-1" @change="apply"><option value="">Todos</option><option value="1">Permitido</option><option value="0">No permitido</option></select></label>
                    <label v-if="catalogSupports('is_available')" class="text-sm font-semibold">Disponibilidad<select v-model="filters.is_available" class="field mt-1" @change="apply"><option value="">Todas</option><option value="1">Disponible</option><option value="0">No disponible</option></select></label>
                    <label v-if="catalogSupports('type')" class="text-sm font-semibold">Tipo<input v-model="filters.type" class="field mt-1" @keyup.enter="apply"></label>
                </div>
                <div class="mt-4 flex flex-wrap gap-2"><button class="min-h-11 rounded-lg bg-blue-600 px-4 font-bold text-white" :disabled="loading" @click="apply">Aplicar</button><button class="min-h-11 rounded-lg border px-4 font-bold" :disabled="loading" @click="clearFilters">Limpiar</button><button class="min-h-11 rounded-lg border px-4 font-bold" :disabled="loading" @click="load">Actualizar</button><button class="min-h-11 rounded-lg border border-emerald-600 px-4 font-bold text-emerald-700" :disabled="downloading || loading" @click="exportCsv">{{ downloading ? 'Descargando…' : 'Exportar CSV' }}</button></div>
            </section>

            <nav class="flex gap-2 overflow-x-auto rounded-xl bg-white p-2 shadow-sm" aria-label="Tipos de reporte"><button v-for="tab in tabs" :key="tab.key" class="min-h-11 shrink-0 rounded-lg px-4 text-sm font-bold" :class="activeSection === tab.key ? 'bg-blue-600 text-white' : 'text-slate-600 hover:bg-slate-100'" @click="changeSection(tab.key)">{{ tab.label }}</button></nav>
            <p v-if="activeSection === 'inventory'" class="rounded-lg border border-blue-200 bg-blue-50 p-3 text-sm text-blue-900">Fotografía actual del inventario. Los filtros temporales no modifican estas existencias.</p>
            <p v-if="activeSection === 'operations'" class="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">Cola operativa actual. Consultar el reporte no ejecuta acciones ni modifica pedidos.</p>
            <p v-if="activeSection === 'sales'" class="rounded-lg border border-slate-200 bg-slate-50 p-3 text-sm text-slate-700">El total del pedido puede repetirse por cada producto y no debe sumarse directamente por fila.</p>
            <div v-if="error" class="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800" role="alert" aria-live="polite">{{ error }} <button class="ml-3 underline" @click="load">Reintentar</button></div>
            <div v-else-if="loading" class="rounded-xl bg-white p-12 text-center text-slate-500" aria-live="polite">Cargando reporte…</div>
            <div v-else-if="!report" class="rounded-xl bg-white p-12 text-center text-slate-500">Sin resultados.</div>
            <template v-else>
                <section class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4" aria-label="Totales"><article v-for="card in totalCards" :key="card.key" class="rounded-xl bg-white p-4 shadow-sm"><p class="text-xs font-bold uppercase text-slate-500">{{ card.label }}</p><strong class="mt-1 block text-2xl">{{ format(card.value, card.money) }}</strong></article></section>
                <div v-if="report.metadata?.truncated" class="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900">El resultado está truncado al límite de {{ report.metadata.limit }} filas.</div>
                <section class="overflow-hidden rounded-2xl bg-white shadow-sm"><div class="overflow-x-auto"><table class="w-full min-w-[760px] text-left text-sm"><thead class="bg-slate-100 text-xs uppercase text-slate-600"><tr><th v-for="column in columns" :key="column.key" class="whitespace-nowrap p-3">{{ column.label }}</th></tr></thead><tbody><tr v-for="(row, index) in rows" :key="index" class="border-t"><td v-for="column in columns" :key="column.key" class="p-3" :class="column.key === 'has_inconsistency' && row[column.key] ? 'font-bold text-red-700' : ''"><router-link v-if="column.key === 'admin_route' && safeAdminRoute(row[column.key])" :to="row[column.key]" class="font-bold text-blue-700 underline">Revisar</router-link><span v-else>{{ display(row[column.key], column) }}</span></td></tr><tr v-if="!rows.length"><td :colspan="columns.length" class="p-10 text-center text-slate-500">Sin datos para los filtros seleccionados.</td></tr></tbody></table></div></section>
                <footer class="text-xs text-slate-500">Filas: {{ report.metadata?.returned_count ?? 0 }} / {{ report.metadata?.row_count ?? 0 }} · Límite: {{ report.metadata?.limit ?? '—' }} · {{ report.metadata?.snapshot_at || report.generated_at || '—' }}</footer>
            </template>
        </div>
    </AdminLayout>
</template>

<script setup>
import { computed, onMounted, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import AdminLayout from '@/layouts/AdminLayout.vue';
import api from '@/api';

const route = useRoute(); const router = useRouter();
const tabs = [{ key: 'sales', label: 'Ventas' }, { key: 'inventory', label: 'Inventario' }, { key: 'inventory_movements', label: 'Movimientos' }, { key: 'operations', label: 'Operaciones' }, { key: 'cycle_times', label: 'Tiempos de ciclo' }, { key: 'catalogs', label: 'Catálogos' }];
const catalogOptions = [{ key: 'products', label: 'Productos' }, { key: 'categories', label: 'Categorías' }, { key: 'brands', label: 'Marcas' }, { key: 'warehouses', label: 'Almacenes' }, { key: 'branches', label: 'Sedes' }, { key: 'drivers', label: 'Repartidores' }, { key: 'vehicles', label: 'Vehículos' }, { key: 'departments', label: 'Departamentos' }, { key: 'provinces', label: 'Provincias' }, { key: 'districts', label: 'Distritos' }, { key: 'shipping_zones', label: 'Zonas de envío' }, { key: 'shipping_rates', label: 'Tarifas de envío' }];
const validSections = tabs.map(x => x.key); const activeSection = ref(validSections.includes(route.query.tab) ? route.query.tab : 'sales');
const filterMap = { sales: ['period', 'date_from', 'date_to', 'delivery_type', 'category_id', 'brand_id', 'payment_method'], inventory: ['category_id', 'brand_id', 'warehouse_id'], inventory_movements: ['period', 'date_from', 'date_to', 'warehouse_id', 'product_id', 'category_id', 'brand_id', 'movement_type', 'movement_direction'], operations: ['delivery_type', 'severity', 'reason_code', 'stage', 'overdue'], cycle_times: ['period', 'date_from', 'date_to', 'delivery_type', 'metric'], catalogs: ['catalog', 'search', 'is_active'] };
const movementTypes = ['initial', 'manual_in', 'manual_out', 'transfer_in', 'transfer_out', 'sale', 'cancellation_return', 'correction']; const severities = ['critical', 'high', 'medium', 'low', 'information']; const reasonCodes = ['PAYMENT_PENDING_OLD', 'PICKING_NOT_STARTED', 'PICKING_STALLED', 'PACKING_NOT_STARTED', 'PACKING_STALLED', 'READY_NOT_DISPATCHED', 'ASSIGNED_NOT_DISPATCHED', 'RESERVATION_EXPIRING', 'RESERVATION_EXPIRED_ACTIVE', 'PICKUP_WAITING', 'PICKUP_EXPIRING', 'PICKUP_EXPIRED', 'DELIVERY_FAILED', 'DELIVERY_REPROGRAM_REQUIRED']; const stages = ['payment_pending', 'waiting_picking', 'picking', 'packing', 'ready', 'reservation', 'pickup', 'assigned', 'delivery']; const metrics = ['picking_duration', 'packing_duration', 'assignment_to_dispatch', 'dispatch_to_delivery', 'ready_to_delivery', 'total_delivery_cycle', 'ready_to_pickup'];
const catalogFilterMap = { products: ['search', 'is_active', 'category_id', 'brand_id'], categories: ['search', 'is_active'], brands: ['search', 'is_active'], warehouses: ['search', 'is_active', 'branch_id'], branches: ['search', 'is_active', 'allows_pickup'], drivers: ['search', 'is_active', 'is_available'], vehicles: ['search', 'is_active', 'is_available', 'type'], departments: ['search', 'is_active'], provinces: ['search', 'is_active', 'department_id'], districts: ['search', 'is_active', 'department_id', 'province_id'], shipping_zones: ['search', 'is_active'], shipping_rates: ['search', 'is_active', 'zone_id', 'district_id'] };
const filters = ref({ period: route.query.period || 'this_year', date_from: route.query.date_from || '', date_to: route.query.date_to || '', delivery_type: route.query.delivery_type || '', category_id: route.query.category_id || '', brand_id: route.query.brand_id || '', payment_method: route.query.payment_method || '', warehouse_id: route.query.warehouse_id || '', product_id: route.query.product_id || '', movement_type: route.query.movement_type || '', movement_direction: route.query.movement_direction || '', severity: route.query.severity || '', reason_code: route.query.reason_code || '', stage: route.query.stage || '', overdue: route.query.overdue || '', metric: metrics.includes(route.query.metric) ? route.query.metric : '', catalog: catalogOptions.some(x => x.key === route.query.catalog) ? route.query.catalog : 'products', search: route.query.search || '', is_active: route.query.is_active || '', branch_id: route.query.branch_id || '', department_id: route.query.department_id || '', province_id: route.query.province_id || '', zone_id: route.query.zone_id || '', district_id: route.query.district_id || '', allows_pickup: route.query.allows_pickup || '', is_available: route.query.is_available || '', type: route.query.type || '' });
const report = ref(null); const loading = ref(false); const downloading = ref(false); const error = ref(''); const generatedAt = ref('—'); const options = ref({ categories: [], brands: [], warehouses: [], products: [], branches: [], departments: [], provinces: [], zones: [], districts: [] }); const syncingUrl = ref(false); let requestId = 0;
const reportRows = value => value?.rows || value?.metrics || [];
const rows = computed(() => reportRows(report.value));
const totalCards = computed(() => { const t = report.value?.totals || {}; const map = { sales: [['sales', 'Ventas cobradas', true], ['orders', 'Pedidos'], ['units', 'Unidades'], ['line_subtotal', 'Subtotal', true]], inventory: [['physical', 'Físico'], ['reserved', 'Reservado'], ['sellable_available', 'Vendible'], ['reservation_deficit', 'Déficit']], inventory_movements: [['movements', 'Movimientos'], ['units_in', 'Entradas'], ['units_out', 'Salidas'], ['net_units', 'Neto']], operations: [['alerts', 'Alertas'], ['affected_orders', 'Pedidos afectados'], ['critical', 'Críticas'], ['overdue', 'Vencidas']], cycle_times: [['total_samples', 'Muestras'], ['total_missing', 'Faltantes'], ['total_invalid', 'Inválidos']], catalogs: [['records', 'Registros'], ['active', 'Activos'], ['inactive', 'Inactivos']] }; return (map[activeSection.value] || []).map(([key, label, money]) => ({ key, label, money, value: t[key] })); });
const columnSets = { sales: [['recognized_at', 'Fecha'], ['order_number', 'Pedido'], ['delivery_type', 'Modalidad'], ['payment_method', 'Pago'], ['product_name', 'Producto'], ['sku', 'SKU'], ['category_name', 'Categoría'], ['brand_name', 'Marca'], ['quantity', 'Cantidad'], ['historical_unit_price', 'Precio'], ['line_subtotal', 'Subtotal línea'], ['order_total', 'Total pedido']], inventory: [['warehouse_name', 'Almacén'], ['product_name', 'Producto'], ['sku', 'SKU'], ['physical', 'Físico'], ['reserved', 'Reservado'], ['raw_available', 'Disponibilidad'], ['sellable_available', 'Vendible'], ['reservation_deficit', 'Déficit'], ['has_inconsistency', 'Inconsistencia']], inventory_movements: [['occurred_at', 'Fecha'], ['warehouse_name', 'Almacén'], ['product_name', 'Producto'], ['sku', 'SKU'], ['movement_type', 'Tipo'], ['movement_direction', 'Dirección'], ['quantity', 'Cantidad'], ['signed_quantity', 'Cantidad firmada'], ['reference_code', 'Referencia'], ['safe_note', 'Observación']], operations: [['severity', 'Prioridad'], ['order_number', 'Pedido'], ['stage', 'Etapa'], ['delivery_type', 'Modalidad'], ['reason_code', 'Razón'], ['relevant_at', 'Fecha relevante'], ['age_label', 'Antigüedad'], ['deadline_label', 'Plazo'], ['admin_route', 'Acción']], cycle_times: [['key', 'Métrica'], ['available', 'Disponible'], ['sample_count', 'Muestras'], ['missing_count', 'Faltantes'], ['invalid_count', 'Inválidos'], ['average_minutes', 'Promedio'], ['median_minutes', 'Mediana'], ['minimum_minutes', 'Mínimo'], ['maximum_minutes', 'Máximo'], ['source', 'Fuente']], catalogs: [] };
const columns = computed(() => activeSection.value === 'catalogs' ? catalogColumns.value : (columnSets[activeSection.value] || []).map(([key, label]) => ({ key, label }))); const catalogColumns = computed(() => { const r = rows.value[0] || {}; return Object.keys(r).filter(k => !['id', 'email', 'phone', 'document_number', 'plate_number', 'address'].includes(k)).map(k => ({ key: k, label: k.replaceAll('_', ' ') })); });
const show = key => (filterMap[activeSection.value] || []).includes(key);
const catalogSupports = key => activeSection.value === 'catalogs' && (catalogFilterMap[filters.value.catalog] || []).includes(key);
function safeAdminRoute(value) { return typeof value === 'string' && value.startsWith('/admin/') && !value.includes('://') && !value.includes('..') && !/[\r\n]/.test(value); }
const safeParams = () => { const allowed = activeSection.value === 'catalogs' ? (catalogFilterMap[filters.value.catalog] || []) : (filterMap[activeSection.value] || []); return Object.fromEntries(Object.entries({ ...filters.value, tab: activeSection.value }).filter(([key, value]) => (key === 'tab' || allowed.includes(key)) && value !== '' && value !== null && value !== undefined)); };
async function syncUrl() { syncingUrl.value = true; await router.replace({ query: safeParams() }); }
async function load() { const id = ++requestId; loading.value = true; error.value = ''; try { const response = await api.get(`/admin/reports/management/${activeSection.value}`, { params: safeParams() }); if (id !== requestId) return; report.value = response.data; generatedAt.value = new Date().toLocaleString('es-PE', { timeZone: 'America/Lima' }); } catch (e) { if (id === requestId) { report.value = null; error.value = e.response?.status === 403 ? 'No tienes permisos para consultar reportes.' : e.response?.status === 422 ? 'Revisa los filtros seleccionados.' : 'No se pudo cargar el reporte.'; } } finally { if (id === requestId) loading.value = false; } }
async function apply() { if (['inventory_movements', 'cycle_times', 'sales'].includes(activeSection.value) && filters.value.period === 'custom' && (!filters.value.date_from || !filters.value.date_to)) { error.value = 'Completa las fechas Desde y Hasta para consultar el rango personalizado.'; report.value = null; return; } await syncUrl(); await load(); }
async function clearFilters() { Object.keys(filters.value).forEach(key => { if (key !== 'period' && key !== 'catalog') filters.value[key] = ''; }); filters.value.period = 'this_year'; await apply(); }
async function changeSection(section) { if (!validSections.includes(section) || section === activeSection.value) return; activeSection.value = section; Object.keys(filters.value).forEach(key => { if (!(filterMap[section] || []).includes(key) && key !== 'catalog') filters.value[key] = ''; }); await syncUrl(); await load(); }
async function catalogChanged() { Object.keys(filters.value).forEach(key => { if (!(catalogFilterMap[filters.value.catalog] || []).includes(key) && !['period', 'catalog'].includes(key)) filters.value[key] = ''; }); await apply(); }
function format(value, money) { const n = Number(value); if (!Number.isFinite(n)) return '—'; return money ? `S/ ${n.toLocaleString('es-PE', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : n.toLocaleString('es-PE'); }
function display(value, column) { if (value === null || value === undefined || value === '') return '—'; if (column.key === 'is_active' || column.key === 'available' || column.key === 'has_inconsistency') return value ? 'Sí' : 'No'; if (typeof value === 'number' && /price|subtotal|amount|total/.test(column.key)) return format(value, true); return String(value); }
async function exportCsv() { if (downloading.value) return; downloading.value = true; let objectUrl = null; try { const response = await api.get(`/admin/reports/management/${activeSection.value}/export`, { params: safeParams(), responseType: 'blob' }); if (!(response.data instanceof Blob) || response.data.type.includes('application/json')) { const payload = JSON.parse(await response.data.text()); throw new Error(payload.message || 'Error de exportación'); } const disposition = response.headers['content-disposition'] || ''; const extended = disposition.match(/filename\*=UTF-8''([^;\r\n]+)/i); const basic = disposition.match(/filename="?([^";\r\n]+)"?/i); const candidate = decodeURIComponent(extended?.[1] || basic?.[1] || ''); const filename = /^[A-Za-z0-9._-]+\.csv$/.test(candidate) ? candidate : `reporte-${activeSection.value}.csv`; objectUrl = URL.createObjectURL(response.data); const link = document.createElement('a'); link.href = objectUrl; link.download = filename; link.click(); } catch (e) { if (e.response?.data instanceof Blob) { try { const payload = JSON.parse(await e.response.data.text()); error.value = payload.message || 'No se pudo exportar el reporte.'; } catch { error.value = 'No se pudo exportar el reporte.'; } } else { error.value = e.message || 'No se pudo exportar el reporte.'; } } finally { if (objectUrl) URL.revokeObjectURL(objectUrl); downloading.value = false; } }
watch(() => route.query, async query => { if (syncingUrl.value) { syncingUrl.value = false; return; } activeSection.value = validSections.includes(query.tab) ? query.tab : 'sales'; Object.keys(filters.value).forEach(key => { filters.value[key] = query[key] || (key === 'period' ? 'this_year' : key === 'catalog' ? 'products' : ''); }); await load(); }, { deep: true });
onMounted(load);
onMounted(async () => { try { const [categories, brands, warehouses, products, branches] = await Promise.all([api.get('/admin/categories/options'), api.get('/admin/brands/options'), api.get('/admin/warehouses/options'), api.get('/products?per_page=100'), api.get('/admin/branches/options')]); options.value = { ...options.value, categories: categories.data.data || categories.data || [], brands: brands.data.data || brands.data || [], warehouses: warehouses.data.data || warehouses.data || [], products: products.data.data || products.data || [], branches: branches.data.data || branches.data || [] }; } catch { /* Los selectores opcionales no bloquean el reporte. */ } });
</script>

<style scoped>
.field { min-height: 2.75rem; width: 100%; border: 1px solid #cbd5e1; border-radius: .5rem; padding: .5rem .75rem; background: white; }
</style>
