<template><AdminLayout><div class="container mx-auto px-6 py-8">
<h1 class="text-gray-700 text-3xl font-medium mb-6">Preparacion y entrega de pedidos</h1>
<div v-if="loading" class="bg-white rounded shadow p-8 text-center">Cargando pedidos...</div><div v-else-if="loadError" class="bg-white rounded shadow p-8 text-center text-red-600">{{loadError}} <button @click="fetchOrders" class="underline">Reintentar</button></div>
<div v-else class="bg-white shadow rounded-lg overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-100 text-xs uppercase"><tr><th class="p-4 text-left">Pedido / cliente</th><th class="p-4">Pago</th><th class="p-4">Estado operativo</th><th class="p-4">Almacen / reserva</th><th class="p-4">Acciones</th></tr></thead><tbody>
<tr v-for="order in orders" :key="order.id" class="border-t"><td class="p-4"><b>#{{order.id}} · {{order.user?.name||'Invitado'}}</b><div class="text-gray-500">{{formatDate(order.created_at)}} · S/ {{order.total}}</div></td><td class="p-4 text-center"><div class="uppercase text-xs">{{order.payment_method}}</div><span :class="order.payment_status==='approved'?'text-green-700':'text-amber-700'">{{order.payment_status}}</span></td><td class="p-4 text-center"><span class="bg-blue-100 text-blue-800 rounded-full px-2 py-1">{{stateLabel(order.fulfillment_status||legacyState(order))}}</span></td><td class="p-4 text-center"><div>{{order.items?.[0]?.warehouse?.name||'—'}}</div><div class="text-xs text-gray-500">{{order.items?.[0]?.reservation?.status||'legacy'}}</div></td><td class="p-4 text-center"><button @click="openOrder(order)" class="text-blue-600"><i class="pi pi-eye mr-1"></i>Gestionar</button></td></tr>
</tbody></table></div>

<div v-if="selectedOrder" class="fixed inset-0 z-50 bg-black/50 overflow-y-auto p-4"><div class="bg-white rounded-lg shadow-xl max-w-4xl mx-auto my-8 p-6">
<div class="flex justify-between mb-5"><div><h2 class="text-xl font-bold">Pedido #{{selectedOrder.id}}</h2><p class="text-gray-500">{{selectedOrder.user?.name}} · {{selectedOrder.payment_method}} · Pago {{selectedOrder.payment_status}}</p></div><button @click="closeModal" class="text-2xl">&times;</button></div>
<div v-if="detailLoading" class="p-8 text-center">Cargando detalle...</div><template v-else>
<div class="grid md:grid-cols-3 gap-3 mb-5"><Info label="Estado operativo" :value="fulfillment.label"/><Info label="Almacen" :value="fulfillment.warehouse?.name||'—'"/><Info label="Reserva" :value="`${fulfillment.reservation_status} · ${fulfillment.expires_at?formatDate(fulfillment.expires_at):'sin vencimiento'}`"/><Info label="Preparacion" :value="stepText(fulfillment.preparing_at,fulfillment.prepared_by)"/><Info label="Listo" :value="stepText(fulfillment.ready_at,fulfillment.ready_by)"/><Info label="Entrega" :value="stepText(fulfillment.delivered_at,fulfillment.delivered_by)"/></div>
<div class="flex flex-wrap gap-3 mb-6">
<button v-if="fulfillment.actions?.approve_payment" @click="confirmAction('approve')" class="bg-emerald-600 text-white px-4 py-2 rounded">Aprobar transferencia</button>
<button v-if="fulfillment.actions?.start_preparation" @click="confirmAction('start')" class="bg-blue-600 text-white px-4 py-2 rounded">Iniciar preparacion</button>
<button v-if="fulfillment.actions?.mark_ready" @click="confirmAction('ready')" class="bg-indigo-600 text-white px-4 py-2 rounded">Marcar como listo</button>
<button v-if="fulfillment.actions?.mark_delivered" @click="confirmAction('delivered')" class="bg-green-600 text-white px-4 py-2 rounded">Marcar como entregado</button>
<button v-if="fulfillment.actions?.cancel" @click="confirmAction('cancel')" class="bg-red-600 text-white px-4 py-2 rounded">Cancelar pedido</button>
</div>
<h3 class="font-bold border-b pb-2 mb-2">Productos</h3><div v-for="item in selectedOrder.items" :key="item.id" class="py-2 border-b flex justify-between"><div>{{item.product?.name}}<div class="text-xs text-gray-500">{{item.warehouse?.name}} · reserva {{item.reservation?.status||'legacy'}}</div></div><b>{{item.quantity}} × S/ {{item.price}}</b></div>
<h3 class="font-bold border-b pb-2 mt-6 mb-2">Historial operativo</h3><div v-if="!fulfillment.history?.length" class="text-gray-500 py-3">Sin transiciones registradas.</div><div v-for="entry in fulfillment.history" :key="entry.id" class="border-l-4 border-blue-300 pl-3 py-2"><b>{{stateLabel(entry.from_status)}} → {{stateLabel(entry.to_status)}}</b><div class="text-xs text-gray-500">{{formatDate(entry.created_at)}} · {{entry.user?.name||'Sistema'}}</div><p v-if="entry.observation" class="text-sm">{{entry.observation}}</p></div>
</template></div></div>
</div></AdminLayout></template>
<script setup>
import {defineComponent,h,onMounted,ref} from 'vue';import AdminLayout from '@/layouts/AdminLayout.vue';import api from '@/api';import{useToast}from'primevue/usetoast';import{useConfirm}from'primevue/useconfirm';import{formatDateTime}from'@/utils/dateTime';
const Info=defineComponent({props:{label:String,value:String},setup(p){return()=>h('div',{class:'bg-gray-50 rounded p-3'},[h('div',{class:'text-xs text-gray-500 uppercase'},p.label),h('div',{class:'font-semibold mt-1'},p.value)])}});
const toast=useToast(),confirm=useConfirm();const orders=ref([]),selectedOrder=ref(null),fulfillment=ref({actions:{}}),loading=ref(true),detailLoading=ref(false),loadError=ref('');
const stateLabel=s=>({reserved:'Reservado',preparing:'En preparacion',ready:'Listo para entrega',delivered:'Entregado',canceled:'Cancelado'}[s]||s||'Reservado');const legacyState=o=>['canceled','rejected'].includes(o.status)?'canceled':o.status==='delivered'?'delivered':'reserved';const formatDate=formatDateTime;const stepText=(date,user)=>date?`${formatDate(date)} · ${user?.name||'Sistema'}`:'Pendiente';
async function fetchOrders(){loading.value=true;loadError.value='';try{orders.value=(await api.get('/admin/orders')).data.data}catch(e){loadError.value=e.response?.data?.message||'No se pudieron cargar los pedidos.'}finally{loading.value=false}}
async function openOrder(order){selectedOrder.value=order;detailLoading.value=true;try{const{data}=await api.get(`/admin/orders/${order.id}/fulfillment`);selectedOrder.value=data.order;fulfillment.value=data.fulfillment}catch(e){error(e);selectedOrder.value=null}finally{detailLoading.value=false}}
function closeModal(){selectedOrder.value=null;fulfillment.value={actions:{}}}
function confirmAction(action){const isCod=selectedOrder.value.payment_method==='contra_entrega';const messages={approve:'¿Confirmar la recepcion de la transferencia? Se consumira la reserva.',start:isCod?'Al iniciar la preparacion se descontara el inventario fisico reservado.':'¿Iniciar la preparacion del pedido?',ready:'¿Marcar el pedido como listo para entrega?',delivered:isCod?'¿Confirmar entrega y pago contraentrega?':'¿Marcar el pedido como entregado?',cancel:'La cancelacion liberara la reserva o repondra el inventario consumido.'};confirm.require({message:messages[action],header:'Confirmacion',icon:'pi pi-exclamation-triangle',accept:()=>runAction(action)})}
async function runAction(action){let payload={observation:null};if(action==='cancel'){const reason=window.prompt('Motivo obligatorio de cancelacion:');if(!reason)return;payload={reason}}const paths={approve:'approve-transfer',start:'start-preparation',ready:'ready',delivered:'delivered',cancel:'cancel'};try{const{data}=await api.post(`/admin/orders/${selectedOrder.value.id}/fulfillment/${paths[action]}`,payload);selectedOrder.value=data.order;fulfillment.value=data.fulfillment;toast.add({severity:'success',summary:'Pedido actualizado',detail:data.fulfillment.label,life:2500});await fetchOrders()}catch(e){error(e)}}
function error(e){toast.add({severity:'error',summary:'Operacion no completada',detail:e.response?.data?.message||Object.values(e.response?.data?.errors||{})[0]?.[0]||e.message,life:4500})}
onMounted(fetchOrders);
</script>
