<template>
<AdminLayout><div class="container mx-auto px-4 py-8"><h1 class="mb-6 text-3xl font-medium text-slate-700">Preparación y entrega de pedidos</h1>
<div v-if="loading" class="rounded bg-white p-8 text-center shadow">Cargando pedidos…</div><div v-else-if="loadError" class="rounded bg-white p-8 text-center text-red-600 shadow">{{loadError}} <button class="underline" @click="fetchOrders">Reintentar</button></div>
<div v-else class="overflow-x-auto rounded-lg bg-white shadow"><table class="min-w-full text-sm"><thead class="bg-slate-100 text-xs uppercase"><tr><th class="p-4 text-left">Pedido / cliente</th><th class="p-4">Pago</th><th class="p-4">Estado</th><th class="p-4">Almacén / reserva</th><th class="p-4">Acción</th></tr></thead><tbody><tr v-for="order in orders" :key="order.id" class="border-t"><td class="p-4"><b>#{{order.id}} · {{order.user?.name||'Invitado'}}</b><div class="text-slate-500">{{formatDate(order.created_at)}} · S/ {{order.total}}</div><div class="mt-1 text-xs font-semibold text-blue-700">{{order.delivery_type==='pickup'?'Recojo en sede':'Envío a domicilio'}}<template v-if="order.delivery_type==='pickup'"> · {{order.pickup_branch_name_snapshot||'Sede histórica'}}</template></div></td><td class="p-4 text-center"><div class="text-xs uppercase">{{order.payment_method}}</div><span :class="order.payment_status==='approved'?'text-green-700':'text-amber-700'">{{order.payment_status}}</span></td><td class="p-4 text-center"><span class="rounded-full bg-blue-100 px-2 py-1 text-blue-800">{{stateLabel(order.fulfillment_status||legacyState(order),order)}}</span></td><td class="p-4 text-center"><div>{{order.items?.[0]?.warehouse?.name||'—'}}</div><div class="text-xs text-slate-500">{{order.items?.[0]?.reservation?.status||'legacy'}}</div></td><td class="p-4 text-center"><button class="text-blue-600" @click="openOrder(order)"><i class="pi pi-eye mr-1"></i>Gestionar</button></td></tr></tbody></table></div>

<div v-if="selectedOrder" class="fixed inset-0 z-50 overflow-y-auto bg-black/50 p-4"><div class="mx-auto my-8 max-w-4xl rounded-lg bg-white p-6 shadow-xl"><div class="mb-5 flex justify-between"><div><h2 class="text-xl font-bold">Pedido #{{selectedOrder.id}}</h2><p class="text-slate-500">{{selectedOrder.user?.name}} · {{selectedOrder.payment_method}} · Pago {{selectedOrder.payment_status}}</p></div><button class="text-2xl" @click="closeModal">&times;</button></div>
<div v-if="detailLoading" class="p-8 text-center">Cargando detalle…</div><template v-else>
<div class="mb-5 grid gap-3 md:grid-cols-3"><Info label="Estado operativo" :value="fulfillment.label"/><Info label="Almacén reservado" :value="fulfillment.warehouse?.name||'—'"/><Info label="Reserva" :value="`${fulfillment.reservation_status} · ${fulfillment.expires_at?formatDate(fulfillment.expires_at):'sin vencimiento'}`"/><Info label="Preparación" :value="stepText(fulfillment.preparing_at,fulfillment.prepared_by)"/><Info :label="selectedOrder.delivery_type==='pickup'?'Listo para recoger':'Listo'" :value="stepText(fulfillment.ready_at,fulfillment.ready_by)"/><Info :label="selectedOrder.delivery_type==='pickup'?'Recogido':'Entrega'" :value="stepText(fulfillment.picked_up_at||fulfillment.delivered_at,fulfillment.delivered_by)"/></div>
<div v-if="selectedOrder.delivery_type==='pickup'" class="mb-5 rounded-lg border border-blue-200 bg-blue-50 p-4"><b>Recojo en sede · {{selectedOrder.pickup_branch_name_snapshot||'Sede histórica'}}</b><p class="text-sm">{{selectedOrder.pickup_address_snapshot}}<template v-if="selectedOrder.pickup_district_snapshot"> — {{selectedOrder.pickup_district_snapshot}}</template></p><p v-if="selectedOrder.pickup_business_hours_snapshot" class="text-sm">Horario: {{selectedOrder.pickup_business_hours_snapshot}}</p><p v-if="selectedOrder.pickup_instructions_snapshot" class="text-sm">{{selectedOrder.pickup_instructions_snapshot}}</p><p class="mt-2 text-sm"><b>Plazo:</b> {{deadlineLabel(fulfillment.pickup_deadline_status)}}<template v-if="fulfillment.pickup_deadline_at"> · hasta {{formatDate(fulfillment.pickup_deadline_at)}}</template></p></div>
<div v-else class="mb-5 rounded-lg border border-slate-200 bg-slate-50 p-4"><b>Envío a domicilio</b><p class="text-sm">{{selectedOrder.shipping_info?.address}}<template v-if="selectedOrder.shipping_district_snapshot"> — {{selectedOrder.shipping_district_snapshot}}</template></p><p class="text-sm">Zona: {{selectedOrder.shipping_zone_name_snapshot||'Configuración histórica'}} · Envío S/ {{selectedOrder.shipping_amount||'0.00'}}</p><p v-if="selectedOrder.shipping_estimated_days_min_snapshot!=null" class="text-sm">Plazo estimado: {{selectedOrder.shipping_estimated_days_min_snapshot}}–{{selectedOrder.shipping_estimated_days_max_snapshot}} días</p></div>
<div v-if="selectedOrder.payment_method==='transferencia'&&selectedOrder.has_payment_submission" class="mb-5 rounded-lg border border-amber-200 bg-amber-50 p-4 text-amber-900"><span class="font-semibold">{{paymentSubmissionLabel(selectedOrder.payment_submission_status)}}</span><p class="mt-1 text-sm">Este pago se gestiona desde el flujo de Tesorería.</p></div>
<div class="mb-6 flex flex-wrap gap-3"><button v-if="fulfillment.actions?.approve_payment&&!selectedOrder.has_payment_submission" class="rounded bg-emerald-600 px-4 py-2 text-white" @click="confirmAction('approve')">Aprobar transferencia</button><button v-if="fulfillment.actions?.start_preparation" class="rounded bg-blue-600 px-4 py-2 text-white" @click="confirmAction('start')">Iniciar preparación</button><button v-if="fulfillment.actions?.mark_ready" class="rounded bg-indigo-600 px-4 py-2 text-white" @click="confirmAction('ready')">{{selectedOrder.delivery_type==='pickup'?'Listo para recoger':'Marcar como listo'}}</button><button v-if="fulfillment.actions?.mark_picked_up" class="rounded bg-green-600 px-4 py-2 text-white" @click="confirmAction('picked')">Pedido recogido</button><button v-if="fulfillment.actions?.mark_delivered" class="rounded bg-green-600 px-4 py-2 text-white" @click="confirmAction('delivered')">Marcar como entregado</button><button v-if="fulfillment.actions?.cancel" class="rounded bg-red-600 px-4 py-2 text-white" @click="confirmAction('cancel')">Cancelar pedido</button></div>
<OrderPickingPackingPanel v-if="handling" :order-id="selectedOrder.id" :summary="handling" @updated="handlingUpdated"/><OrderDeliveryPanel v-if="selectedOrder.delivery_type!=='pickup'&&(fulfillment.status==='ready'||fulfillment.status==='delivered')" :order-id="selectedOrder.id" :initial="delivery" @updated="deliveryUpdated"/>
<h3 class="mb-2 border-b pb-2 font-bold">Productos</h3><div v-for="item in selectedOrder.items" :key="item.id" class="flex justify-between border-b py-2"><div>{{item.product?.name}}<div class="text-xs text-slate-500">{{item.warehouse?.name}} · reserva {{item.reservation?.status||'legacy'}}</div></div><b>{{item.quantity}} × S/ {{item.price}}</b></div>
<h3 class="mb-2 mt-6 border-b pb-2 font-bold">Historial operativo</h3><div v-if="!fulfillment.history?.length" class="py-3 text-slate-500">Sin transiciones registradas.</div><div v-for="entry in fulfillment.history" :key="entry.id" class="border-l-4 border-blue-300 py-2 pl-3"><b>{{stateLabel(entry.from_status)}} → {{stateLabel(entry.to_status)}}</b><div class="text-xs text-slate-500">{{formatDate(entry.created_at)}} · {{entry.user?.name||'Sistema'}}</div><p v-if="entry.observation" class="text-sm">{{entry.observation}}</p></div>
</template></div></div></div></AdminLayout>
</template>
<script setup>
import{defineComponent,h,onMounted,ref}from'vue';import AdminLayout from '@/layouts/AdminLayout.vue';import OrderPickingPackingPanel from '@/components/admin/OrderPickingPackingPanel.vue';import OrderDeliveryPanel from '@/components/admin/OrderDeliveryPanel.vue';import api from '@/api';import{useToast}from'primevue/usetoast';import{useConfirm}from'primevue/useconfirm';import{formatDateTime}from'@/utils/dateTime';
const Info=defineComponent({props:{label:String,value:String},setup:p=>()=>h('div',{class:'rounded bg-slate-50 p-3'},[h('div',{class:'text-xs uppercase text-slate-500'},p.label),h('div',{class:'mt-1 font-semibold'},p.value)])});
const toast=useToast(),confirm=useConfirm(),orders=ref([]),selectedOrder=ref(null),fulfillment=ref({actions:{}}),handling=ref(null),delivery=ref(null),loading=ref(true),detailLoading=ref(false),loadError=ref('');
const stateLabel=(s,o)=>({reserved:'Reservado',preparing:'En preparación',ready:o?.delivery_type==='pickup'?'Listo para recoger':'Listo para entrega',delivered:o?.delivery_type==='pickup'?'Recogido':'Entregado',canceled:'Cancelado'}[s]||s||'Reservado');const legacyState=o=>['canceled','rejected'].includes(o.status)?'canceled':o.status==='delivered'?'delivered':'reserved';const deadlineLabel=s=>({preparing:'En preparación',within_deadline:'Dentro del plazo',expired:'Recojo vencido · requiere revisión administrativa',picked_up:'Recogido',not_applicable:'No aplica'}[s]||s);const paymentSubmissionLabel=s=>({pending_review:'Pendiente de Tesorería',observed:'Observado por Tesorería',approved:'Aprobado por Tesorería',rejected:'Rechazado por Tesorería',expired:'Presentación vencida',canceled:'Presentación cancelada'}[s]||'Pago gestionado por Tesorería');const formatDate=formatDateTime;const stepText=(d,u)=>d?`${formatDate(d)} · ${u?.name||'Sistema'}`:'Pendiente';
async function fetchOrders(){loading.value=true;loadError.value='';try{orders.value=(await api.get('/admin/orders')).data.data}catch(e){loadError.value=e.response?.data?.message||'No se pudieron cargar los pedidos.'}finally{loading.value=false}}
async function openOrder(order){selectedOrder.value=order;detailLoading.value=true;try{const{data}=await api.get(`/admin/orders/${order.id}/fulfillment`);selectedOrder.value=data.order;fulfillment.value=data.fulfillment;handling.value=data.fulfillment.picking_packing||null;if(order.delivery_type!=='pickup')delivery.value=(await api.get(`/admin/orders/${order.id}/delivery`)).data}catch(e){showError(e);selectedOrder.value=null}finally{detailLoading.value=false}}
function closeModal(){selectedOrder.value=null;fulfillment.value={actions:{}};handling.value=null;delivery.value=null}function handlingUpdated(v){handling.value=v;fulfillment.value.picking_packing=v;fulfillment.value.actions.mark_ready=Boolean(v.actions?.mark_ready)}async function deliveryUpdated(v){delivery.value=v;if(v.order?.fulfillment_status==='delivered')await openOrder({id:selectedOrder.value.id,delivery_type:'delivery'});await fetchOrders()}
function confirmAction(action){const messages={approve:'¿Confirmar la recepción de la transferencia?',start:'¿Iniciar la preparación?',ready:selectedOrder.value.delivery_type==='pickup'?'¿Marcar como listo para recoger e iniciar el plazo de 10 días hábiles?':'¿Marcar como listo?',picked:'¿Confirmar que el cliente recogió el pedido?',delivered:'¿Marcar como entregado?',cancel:'La cancelación afectará la reserva o el inventario consumido.'};confirm.require({message:messages[action],header:'Confirmación',accept:()=>runAction(action)})}
async function runAction(action){let payload={observation:null};if(action==='cancel'){const reason=window.prompt('Motivo obligatorio:');if(!reason)return;payload={reason}}if(action==='picked'&&['contra_entrega','pago_en_sede'].includes(selectedOrder.value.payment_method)){const method=window.prompt('Medio: cash, card_terminal, bank_transfer u other','cash');if(!method)return;payload={money_received:true,collection_method:method}}const paths={approve:'approve-transfer',start:'start-preparation',ready:selectedOrder.value.delivery_type==='pickup'?'ready-for-pickup':'ready',picked:'picked-up',delivered:'delivered',cancel:'cancel'};try{const{data}=await api.post(`/admin/orders/${selectedOrder.value.id}/fulfillment/${paths[action]}`,payload);selectedOrder.value=data.order;fulfillment.value=data.fulfillment;handling.value=data.fulfillment.picking_packing||handling.value;toast.add({severity:'success',summary:'Pedido actualizado',life:2500});await fetchOrders()}catch(e){showError(e)}}function showError(e){toast.add({severity:'error',summary:'Operación no completada',detail:e.response?.data?.message||Object.values(e.response?.data?.errors||{})[0]?.[0]||e.message,life:4500})}onMounted(fetchOrders);
</script>
