<template>
    <AdminLayout>
        <div class="space-y-6">
            <header class="flex flex-wrap items-center justify-between gap-3"><div><h1 class="text-2xl font-black text-slate-900">Tarifas de envío</h1><p class="text-sm text-slate-600">Zonas operativas y cobertura por distrito.</p></div><button class="min-h-11 rounded-lg bg-blue-700 px-4 font-bold text-white" @click="openZone()">Nueva zona</button></header>

            <section class="rounded-xl bg-white p-4 shadow">
                <div class="mb-4 grid gap-3 sm:grid-cols-[1fr_12rem]"><input v-model="filters.search" placeholder="Buscar zona o código" class="min-h-11 rounded-lg border px-3" @keyup.enter="loadZones"><select v-model="filters.is_active" class="min-h-11 rounded-lg border px-3" @change="loadZones"><option value="">Todos los estados</option><option value="1">Activas</option><option value="0">Inactivas</option></select></div>
                <div v-if="loading" class="py-8 text-center text-slate-500">Cargando…</div><div v-else class="overflow-x-auto"><table class="w-full min-w-[720px] text-left text-sm"><thead><tr class="border-b text-slate-500"><th class="p-3">Zona</th><th class="p-3">Plazo</th><th class="p-3">Distritos</th><th class="p-3">Estado</th><th class="p-3">Acciones</th></tr></thead><tbody><tr v-for="zone in zones" :key="zone.id" class="border-b"><td class="p-3"><b>{{ zone.name }}</b><div class="font-mono text-xs">{{ zone.code }}</div></td><td class="p-3">{{ days(zone.estimated_days_min, zone.estimated_days_max) }}</td><td class="p-3">{{ zone.covered_districts_count }} con cobertura / {{ zone.rates_count }}</td><td class="p-3"><span :class="zone.is_active ? 'bg-emerald-100 text-emerald-800' : 'bg-slate-200 text-slate-700'" class="rounded-full px-2 py-1 font-bold">{{ zone.is_active ? 'Activa' : 'Inactiva' }}</span></td><td class="p-3"><button class="mr-3 font-bold text-blue-700" @click="openZone(zone)">Editar</button><button class="font-bold" :class="zone.is_active ? 'text-red-700' : 'text-emerald-700'" @click="toggleZone(zone)">{{ zone.is_active ? 'Desactivar' : 'Activar' }}</button></td></tr></tbody></table><p v-if="!zones.length" class="py-8 text-center text-slate-500">No se encontraron zonas.</p></div>
            </section>

            <section class="rounded-xl bg-white p-4 shadow">
                <div class="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-xl font-black">Distritos y tarifas</h2><p class="text-sm text-slate-600">Una tarifa activa equivale a cobertura vigente si su zona también está activa.</p></div><button :disabled="!zones.length" class="min-h-11 rounded-lg bg-blue-700 px-4 font-bold text-white disabled:opacity-50" @click="openRate()">Nueva tarifa</button></div>
                <div class="mb-4 grid gap-3 md:grid-cols-3"><input v-model="rateFilters.search" placeholder="Zona, departamento, provincia o distrito" class="min-h-11 rounded-lg border px-3" @keyup.enter="loadRates"><select v-model="rateFilters.shipping_zone_id" class="min-h-11 rounded-lg border px-3" @change="loadRates"><option value="">Todas las zonas</option><option v-for="zone in zones" :key="zone.id" :value="zone.id">{{ zone.name }}</option></select><select v-model="rateFilters.is_active" class="min-h-11 rounded-lg border px-3" @change="loadRates"><option value="">Todos los estados</option><option value="1">Con cobertura activa</option><option value="0">Sin cobertura</option></select></div>
                <div class="overflow-x-auto"><table class="w-full min-w-[860px] text-left text-sm"><thead><tr class="border-b text-slate-500"><th class="p-3">Ubicación</th><th class="p-3">Zona</th><th class="p-3">Tarifa</th><th class="p-3">Plazo</th><th class="p-3">Cobertura</th><th class="p-3">Acciones</th></tr></thead><tbody><tr v-for="rate in rates" :key="rate.id" class="border-b"><td class="p-3"><b>{{ rate.district_relation?.name || rate.district }}</b><div>{{ rate.district_relation?.province?.name || rate.province }} — {{ rate.district_relation?.province?.department?.name || rate.department }}</div><small v-if="rate.district_relation?.ubigeo || rate.ubigeo">Ubigeo {{ rate.district_relation?.ubigeo || rate.ubigeo }}</small><div v-if="!rate.district_id" class="mt-1 text-xs font-bold text-amber-700">Pendiente de regularizar</div></td><td class="p-3">{{ rate.zone.name }}</td><td class="p-3 font-bold">S/ {{ money(rate.amount) }}</td><td class="p-3">{{ days(rate.estimated_days_min ?? rate.zone.estimated_days_min, rate.estimated_days_max ?? rate.zone.estimated_days_max) }}</td><td class="p-3"><span :class="rate.is_active && rate.zone.is_active ? 'text-emerald-700' : 'text-amber-700'" class="font-bold">{{ rate.is_active && rate.zone.is_active ? 'Con cobertura' : 'Sin cobertura' }}</span></td><td class="p-3"><button class="mr-3 font-bold text-blue-700" @click="openRate(rate)">Editar</button><button class="font-bold" :class="rate.is_active ? 'text-red-700' : 'text-emerald-700'" @click="toggleRate(rate)">{{ rate.is_active ? 'Desactivar' : 'Activar' }}</button></td></tr></tbody></table><p v-if="!rates.length" class="py-8 text-center text-slate-500">No se encontraron tarifas.</p></div>
            </section>
        </div>

        <div v-if="zoneModal" class="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4" @mousedown.self="zoneModal=false"><form class="w-full max-w-lg space-y-4 rounded-xl bg-white p-6" @submit.prevent="saveZone"><h2 class="text-xl font-black">{{ zoneForm.id ? 'Editar' : 'Nueva' }} zona</h2><label class="block text-sm font-medium">Código<input v-model.trim="zoneForm.code" required maxlength="50" class="mt-1 min-h-11 w-full rounded-lg border px-3"></label><label class="block text-sm font-medium">Nombre<input v-model.trim="zoneForm.name" required class="mt-1 min-h-11 w-full rounded-lg border px-3"></label><label class="block text-sm font-medium">Descripción<textarea v-model.trim="zoneForm.description" class="mt-1 w-full rounded-lg border p-3"></textarea></label><div class="grid grid-cols-2 gap-3"><label class="text-sm font-medium">Días mínimos<input v-model="zoneForm.estimated_days_min" type="number" min="0" class="mt-1 min-h-11 w-full rounded-lg border px-3"></label><label class="text-sm font-medium">Días máximos<input v-model="zoneForm.estimated_days_max" type="number" min="0" class="mt-1 min-h-11 w-full rounded-lg border px-3"></label></div><label class="flex gap-2"><input v-model="zoneForm.is_active" type="checkbox"> Zona activa</label><div class="flex justify-end gap-3"><button type="button" class="min-h-11 px-4" @click="zoneModal=false">Cancelar</button><button class="min-h-11 rounded-lg bg-blue-700 px-4 font-bold text-white">Guardar</button></div></form></div>
        <div v-if="rateModal" class="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-950/60 p-4" @mousedown.self="rateModal=false"><form class="my-6 w-full max-w-xl space-y-4 rounded-xl bg-white p-6" @submit.prevent="saveRate"><h2 class="text-xl font-black">{{ rateForm.id ? 'Editar' : 'Nueva' }} tarifa</h2><label class="block text-sm font-medium">Zona<select v-model="rateForm.shipping_zone_id" required class="mt-1 min-h-11 w-full rounded-lg border px-3"><option disabled value="">Selecciona una zona</option><option v-for="zone in zones" :key="zone.id" :value="zone.id">{{ zone.name }}{{ zone.is_active ? '' : ' (inactiva)' }}</option></select></label><div class="grid gap-3 sm:grid-cols-3"><label class="text-sm font-medium">Departamento<select v-model="rateForm.department_id" required class="mt-1 min-h-11 w-full rounded-lg border px-3" @change="changeRateDepartment"><option :value="null" disabled>Selecciona</option><option v-for="item in departments" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label class="text-sm font-medium">Provincia<select v-model="rateForm.province_id" required :disabled="!rateForm.department_id" class="mt-1 min-h-11 w-full rounded-lg border px-3" @change="changeRateProvince"><option :value="null" disabled>Selecciona</option><option v-for="item in provinces" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label class="text-sm font-medium">Distrito<select v-model="rateForm.district_id" required :disabled="!rateForm.province_id" class="mt-1 min-h-11 w-full rounded-lg border px-3"><option :value="null" disabled>Selecciona</option><option v-for="item in districts" :key="item.id" :value="item.id">{{ item.name }}</option></select></label></div><label class="block text-sm font-medium">Tarifa S/<input v-model.trim="rateForm.amount" required inputmode="decimal" pattern="\d+(\.\d{1,2})?" class="mt-1 min-h-11 w-full rounded-lg border px-3"></label><div class="grid grid-cols-2 gap-3"><label class="text-sm font-medium">Días mínimos<input v-model="rateForm.estimated_days_min" type="number" min="0" class="mt-1 min-h-11 w-full rounded-lg border px-3"></label><label class="text-sm font-medium">Días máximos<input v-model="rateForm.estimated_days_max" type="number" min="0" class="mt-1 min-h-11 w-full rounded-lg border px-3"></label></div><label class="flex gap-2"><input v-model="rateForm.is_active" type="checkbox"> Tarifa activa</label><div class="flex justify-end gap-3"><button type="button" class="min-h-11 px-4" @click="rateModal=false">Cancelar</button><button class="min-h-11 rounded-lg bg-blue-700 px-4 font-bold text-white">Guardar</button></div></form></div>
    </AdminLayout>
</template>

<script setup>
import { onMounted, reactive, ref } from 'vue';
import { useToast } from 'primevue/usetoast';
import api from '@/api';
import AdminLayout from '@/layouts/AdminLayout.vue';

const toast = useToast();
const zones = ref([]), rates = ref([]), loading = ref(false), zoneModal = ref(false), rateModal = ref(false);
const departments = ref([]), provinces = ref([]), districts = ref([]);
const filters = reactive({ search: '', is_active: '' });
const rateFilters = reactive({ search: '', shipping_zone_id: '', is_active: '' });
const emptyZone = () => ({ id: null, code: '', name: '', description: '', estimated_days_min: '', estimated_days_max: '', is_active: true });
const emptyRate = () => ({ id: null, shipping_zone_id: '', department_id: null, province_id: null, district_id: null, amount: '', estimated_days_min: '', estimated_days_max: '', is_active: true });
const zoneForm = reactive(emptyZone()), rateForm = reactive(emptyRate());
const clean = data => Object.fromEntries(Object.entries(data).map(([key, value]) => [key, value === '' ? null : value]));
const money = value => Number(value || 0).toFixed(2);
const days = (min, max) => min == null && max == null ? 'Por confirmar' : min === max ? `${min} día(s)` : `${min ?? 0}–${max ?? min} días`;
const fail = error => toast.add({ severity: 'error', summary: 'No se pudo guardar', detail: Object.values(error.response?.data?.errors || {})[0]?.[0] || error.response?.data?.message || error.message, life: 5000 });
async function loadZones() { loading.value = true; try { zones.value = (await api.get('/admin/shipping-zones', { params: filters })).data.data; } catch (error) { fail(error); } finally { loading.value = false; } }
async function loadRates() { try { rates.value = (await api.get('/admin/shipping-rates', { params: rateFilters })).data.data; } catch (error) { fail(error); } }
function openZone(zone = null) { Object.assign(zoneForm, emptyZone(), zone || {}); zoneModal.value = true; }
async function openRate(rate = null) { Object.assign(rateForm, emptyRate(), rate || {}); if (rate?.district_relation?.province) { rateForm.department_id = rate.district_relation.province.department_id; rateForm.province_id = rate.district_relation.province_id; } provinces.value = rateForm.department_id ? (await api.get('/location/provinces', { params: { department_id: rateForm.department_id } })).data : []; districts.value = rateForm.province_id ? (await api.get('/location/districts', { params: { province_id: rateForm.province_id } })).data : []; rateModal.value = true; }
async function changeRateDepartment() { rateForm.province_id = null; rateForm.district_id = null; districts.value = []; provinces.value = rateForm.department_id ? (await api.get('/location/provinces', { params: { department_id: rateForm.department_id } })).data : []; }
async function changeRateProvince() { rateForm.district_id = null; districts.value = rateForm.province_id ? (await api.get('/location/districts', { params: { province_id: rateForm.province_id } })).data : []; }
async function saveZone() { try { const payload = clean({ ...zoneForm }); delete payload.id; zoneForm.id ? await api.put(`/admin/shipping-zones/${zoneForm.id}`, payload) : await api.post('/admin/shipping-zones', payload); zoneModal.value = false; await Promise.all([loadZones(), loadRates()]); } catch (error) { fail(error); } }
async function saveRate() { try { const payload = clean({ ...rateForm }); delete payload.id; rateForm.id ? await api.put(`/admin/shipping-rates/${rateForm.id}`, payload) : await api.post('/admin/shipping-rates', payload); rateModal.value = false; await Promise.all([loadZones(), loadRates()]); } catch (error) { fail(error); } }
async function toggleZone(zone) { if (!confirm(`¿${zone.is_active ? 'Desactivar' : 'Activar'} la zona ${zone.name}?`)) return; try { await api.patch(`/admin/shipping-zones/${zone.id}/status`, { is_active: !zone.is_active }); await Promise.all([loadZones(), loadRates()]); } catch (error) { fail(error); } }
async function toggleRate(rate) { if (!confirm(`¿${rate.is_active ? 'Desactivar' : 'Activar'} la tarifa de ${rate.district}?`)) return; try { await api.patch(`/admin/shipping-rates/${rate.id}/status`, { is_active: !rate.is_active }); await Promise.all([loadZones(), loadRates()]); } catch (error) { fail(error); } }
onMounted(async () => { departments.value = (await api.get('/location/departments')).data; await Promise.all([loadZones(), loadRates()]); });
</script>
