<template>
<section class="mt-6 rounded-lg border border-cyan-200 bg-white p-4">
  <div class="flex flex-wrap items-center justify-between gap-3"><div><h3 class="text-lg font-bold">Despacho y entrega</h3><p class="text-sm text-gray-500">El inventario ya fue procesado; estas acciones son exclusivamente logísticas.</p></div><span v-if="data?.delivery" class="rounded-full bg-cyan-100 px-3 py-1 text-sm font-semibold text-cyan-800">{{statusLabel(data.delivery.status)}}</span></div>
  <div v-if="loading" class="mt-4 animate-pulse rounded bg-gray-100 p-8 text-center">Cargando despacho...</div>
  <div v-else-if="!data?.available" class="mt-4 rounded border border-dashed p-5 text-center"><p class="text-gray-600">{{data?.message||'El despacho aún no está inicializado.'}}</p><button v-if="data?.can_initialize" :disabled="busy" @click="act('initialize')" class="btn-primary mt-3">Inicializar despacho</button></div>
  <template v-else>
    <div class="mt-4 grid gap-3 md:grid-cols-4"><Info label="Modalidad" :value="methodLabel(data.delivery.method)"/><Info label="Programado" :value="formatDateTime(data.delivery.scheduled_at)"/><Info label="Responsable" :value="data.delivery.delivery_user_name||data.delivery.courier_name||data.delivery.pickup_location_name||'Pendiente'"/><Info label="Cobro" :value="paymentText"/></div>
    <div v-if="data.order.payment_method==='contra_entrega'&&!data.payment_transaction" class="mt-3 rounded border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900">Contraentrega: el cobro se registrará únicamente al confirmar una entrega exitosa.</div>
    <div v-if="data.actions.change_method" class="mt-4 grid gap-2 sm:grid-cols-3"><button v-for="m in methods" :key="m.value" @click="changeMethod(m.value)" :class="data.delivery.method===m.value?'border-blue-600 bg-blue-50':'border-gray-200'" class="rounded border p-3 text-left"><b>{{m.label}}</b><div class="text-xs text-gray-500">{{m.help}}</div></button></div>

    <form v-if="data.delivery.method==='store_pickup'&&data.actions.schedule_pickup" @submit.prevent="schedulePickup" class="form-card">
      <h4 class="font-bold">Programar recojo</h4><select v-model="pickup.warehouse_id" required class="field"><option value="">Punto de recojo</option><option v-for="w in options.warehouses" :key="w.id" :value="w.id">{{w.name}} — {{w.branch?.name}}</option></select><input v-model="pickup.scheduled_at" type="datetime-local" class="field"><input v-model="pickup.time_window" placeholder="Horario o franja" class="field"><input v-model="pickup.authorized_person" placeholder="Persona autorizada (opcional)" class="field"><button :disabled="busy" class="btn-primary">Guardar y esperar recojo</button>
    </form>
    <form v-if="data.delivery.method==='own_delivery'&&data.actions.assign_driver" @submit.prevent="assignDriver" class="form-card"><h4 class="font-bold">Asignar reparto propio</h4><select v-model="driver.delivery_user_id" required class="field"><option value="">Repartidor habilitado</option><option v-for="u in options.drivers" :key="u.id" :value="u.id">{{u.name}}</option></select><input v-model="driver.scheduled_at" type="datetime-local" class="field"><input v-model="driver.vehicle_plate" placeholder="Vehículo o placa" class="field"><button :disabled="busy" class="btn-primary">Asignar repartidor</button></form>
    <form v-if="data.delivery.method==='external_courier'&&data.actions.assign_courier" @submit.prevent="assignCourier" class="form-card"><h4 class="font-bold">Courier externo manual</h4><input v-model="courier.courier_name" required placeholder="Empresa de courier" class="field"><input v-model="courier.courier_service" placeholder="Servicio" class="field"><input v-model="courier.tracking_number" placeholder="Número de guía" class="field"><input v-model="courier.tracking_url" type="url" placeholder="https://seguimiento..." class="field"><input v-model="courier.courier_reference" placeholder="Referencia" class="field"><button :disabled="busy" class="btn-primary">Guardar courier</button></form>

    <div class="mt-4 flex flex-wrap gap-2"><button v-if="data.actions.dispatch" @click="confirmAct('dispatch','¿Registrar la salida del paquete?')" class="btn-primary">Registrar despacho</button><button v-if="data.actions.start_attempt" @click="act('attempts')" class="btn-primary">Iniciar intento</button><button v-if="data.actions.out_for_delivery" @click="confirmAct('out-for-delivery','¿Confirmar que el pedido está en camino?')" class="btn-primary">En camino</button><button v-if="data.actions.fail_attempt" @click="failAttempt" class="btn-danger">Intento fallido</button><button v-if="data.actions.reschedule" @click="reschedule" class="btn-primary">Reprogramar</button><button v-if="data.actions.confirm_delivery" @click="confirmOpen=true" class="btn-success">Confirmar entrega</button><button v-if="data.actions.cancel" @click="cancelDelivery" class="btn-danger">Cancelar antes de salida</button></div>

    <div v-if="data.delivery.attempts?.length" class="mt-5"><h4 class="font-bold">Intentos</h4><div v-for="a in data.delivery.attempts" :key="a.id" class="mt-2 rounded border p-3 text-sm"><b>Intento {{a.attempt_number}} · {{statusLabel(a.status)}}</b><div class="text-gray-500">{{formatDateTime(a.started_at||a.scheduled_at)}}</div><p v-if="a.failure_description" class="text-red-700">{{failureLabel(a.failure_reason)}}: {{a.failure_description}}</p></div></div>
    <details class="mt-5 rounded border p-3"><summary class="cursor-pointer font-semibold">Historial ({{data.delivery.history?.length||0}})</summary><div v-for="h in data.delivery.history" :key="h.id" class="mt-3 border-l-2 border-cyan-300 pl-3 text-sm"><b>{{eventLabel(h.event_type)}}</b><div class="text-xs text-gray-500">{{formatDateTime(h.created_at)}} · {{h.user?.name||'Usuario eliminado'}}</div><p v-if="h.observation">{{h.observation}}</p></div></details>
  </template>

  <div v-if="confirmOpen" class="fixed inset-0 z-[70] flex items-center justify-center overflow-y-auto bg-black/50 p-4"><form @submit.prevent="confirmDelivery" class="my-8 w-full max-w-2xl rounded bg-white p-6"><div class="flex justify-between"><h3 class="text-lg font-bold">Confirmar entrega</h3><button type="button" @click="confirmOpen=false" class="text-2xl">&times;</button></div><div class="mt-4 grid gap-3 md:grid-cols-2"><input v-model="confirmation.recipient_name" required placeholder="Nombre de quien recibe" class="field"><select v-model="confirmation.recipient_document_type" required class="field"><option value="DNI">DNI</option><option value="CE">CE</option><option value="PASSPORT">Pasaporte</option><option value="OTHER">Otro</option></select><input v-model="confirmation.recipient_document_number" required placeholder="Número de documento" class="field"><input v-model="confirmation.relationship_to_customer" placeholder="Relación con cliente" class="field"><select v-model="confirmation.confirmation_method" required class="field"><option value="manual">Manual</option><option value="confirmation_code">Código</option><option value="signature">Firma</option><option value="photo">Foto</option></select><input v-model="confirmation.confirmation_code" placeholder="Código opcional" class="field"><label class="text-sm">Foto<input ref="photo" type="file" accept="image/jpeg,image/png,image/webp" class="field"></label><label class="text-sm">Firma<input ref="signature" type="file" accept="image/jpeg,image/png,image/webp" class="field"></label><textarea v-model="confirmation.delivery_notes" placeholder="Observación" class="field md:col-span-2"></textarea></div><div v-if="data?.order.payment_method==='contra_entrega'" class="mt-4 rounded bg-amber-50 p-3"><label class="flex gap-2 font-semibold"><input v-model="confirmation.money_received" type="checkbox" required> Confirmo que el dinero fue recibido</label><select v-model="confirmation.collection_method" class="field mt-2"><option value="cash">Efectivo</option><option value="card_terminal">POS</option><option value="bank_transfer">Transferencia</option><option value="other">Otro</option></select><input v-model="confirmation.manual_reference" placeholder="Referencia opcional" class="field mt-2"></div><div class="mt-5 flex justify-end gap-2"><button type="button" @click="confirmOpen=false" class="btn-muted">Volver</button><button :disabled="busy" class="btn-success">Confirmar cobro y entrega</button></div></form></div>
</section>
</template>
<script setup>
import{computed,defineComponent,h,onMounted,reactive,ref}from'vue';import api from'@/api';import{formatDateTime}from'@/utils/dateTime';import{useToast}from'primevue/usetoast';import{useConfirm}from'primevue/useconfirm';
const props=defineProps({orderId:{type:Number,required:true},initial:{type:Object,default:null}}),emit=defineEmits(['updated']);const toast=useToast(),confirm=useConfirm(),data=ref(props.initial),options=reactive({warehouses:[],drivers:[]}),loading=ref(!props.initial),busy=ref(false),confirmOpen=ref(false),photo=ref(),signature=ref();
const methods=[{value:'store_pickup',label:'Recojo en tienda',help:'Cliente recoge en un almacén activo.'},{value:'own_delivery',label:'Reparto propio',help:'Responsable interno habilitado.'},{value:'external_courier',label:'Courier externo',help:'Seguimiento manual por guía.'}],pickup=reactive({warehouse_id:'',scheduled_at:'',time_window:'',authorized_person:''}),driver=reactive({delivery_user_id:'',scheduled_at:'',vehicle_plate:''}),courier=reactive({courier_name:'',courier_service:'',tracking_number:'',tracking_url:'',courier_reference:''}),confirmation=reactive({recipient_name:'',recipient_document_type:'DNI',recipient_document_number:'',relationship_to_customer:'',confirmation_method:'manual',confirmation_code:'',delivery_notes:'',money_received:false,collection_method:'cash',manual_reference:''});
const Info=defineComponent({props:{label:String,value:[String,Number]},setup:p=>()=>h('div',{class:'rounded bg-gray-50 p-3'},[h('div',{class:'text-xs uppercase text-gray-500'},p.label),h('b',p.value||'—')])});const paymentText=computed(()=>data.value?.payment_transaction?`${data.value.payment_transaction.status} · ${data.value.payment_transaction.currency} ${data.value.payment_transaction.amount}`:'Pendiente');
const statusLabel=s=>({pending:'Pendiente',scheduled:'Programado',assigned:'Asignado',dispatched:'Despachado',out_for_delivery:'En camino',awaiting_pickup:'Esperando recojo',delivered:'Entregado',failed_attempt:'Intento fallido',rescheduled:'Reprogramado',canceled:'Cancelado',in_progress:'En curso',failed:'Fallido'}[s]||s);const methodLabel=m=>methods.find(x=>x.value===m)?.label||m;const failureLabel=x=>x?.replaceAll('_',' ')||'';const eventLabel=x=>x?.replaceAll('_',' ')||'';
async function load(){loading.value=true;try{data.value=(await api.get(`/admin/orders/${props.orderId}/delivery`)).data;emit('updated',data.value)}catch(e){showError(e)}finally{loading.value=false}}
async function send(path,payload={},method='post',multipart=false){busy.value=true;try{const config=multipart?{headers:{'Content-Type':'multipart/form-data'}}:{};data.value=(await api[method](`/admin/orders/${props.orderId}/delivery/${path}`,payload,config)).data;emit('updated',data.value);toast.add({severity:'success',summary:'Despacho actualizado',life:2200})}catch(e){showError(e);throw e}finally{busy.value=false}}
const act=path=>send(path);function confirmAct(path,message){confirm.require({message,header:'Confirmación operativa',accept:()=>act(path)})}const changeMethod=m=>send('method',{method:m},'patch');const schedulePickup=()=>send('schedule-pickup',pickup);const assignDriver=()=>send('assign-driver',driver);const assignCourier=()=>send('assign-courier',courier);
function failAttempt(){const reason=window.prompt('Motivo: recipient_absent, incorrect_address, recipient_rejected, unable_to_contact, access_restricted, damaged_package, courier_issue, weather_or_traffic u other');if(!reason)return;const description=window.prompt('Descripción obligatoria del fallo:');if(!description)return;const attempt=[...(data.value.delivery.attempts||[])].reverse().find(a=>a.status==='in_progress');if(attempt)send(`attempts/${attempt.id}/fail`,{failure_reason:reason,failure_description:description},'patch')}
function reschedule(){const scheduled_at=window.prompt('Nueva fecha ISO o local (YYYY-MM-DD HH:mm):');if(scheduled_at)send('reschedule',{scheduled_at})}function cancelDelivery(){const reason=window.prompt('Motivo obligatorio:');if(reason)send('cancel',{reason})}
async function confirmDelivery(){const form=new FormData();Object.entries(confirmation).forEach(([k,v])=>form.append(k,k==='money_received'?(v?'1':'0'):v??''));if(photo.value?.files[0])form.append('delivery_photo',photo.value.files[0]);if(signature.value?.files[0])form.append('recipient_signature',signature.value.files[0]);await send('confirm',form,'post',true);confirmOpen.value=false}
function showError(e){toast.add({severity:'error',summary:'Operación no completada',detail:e.response?.data?.message||Object.values(e.response?.data?.errors||{})[0]?.[0]||e.message,life:4500})}
onMounted(async()=>{try{Object.assign(options,(await api.get('/admin/delivery/options')).data)}catch(e){showError(e)}if(!data.value)await load()});
</script>
<style scoped>.field{@apply w-full rounded border border-gray-300 p-2}.form-card{@apply mt-4 grid gap-3 rounded border bg-gray-50 p-4 md:grid-cols-2}.form-card h4{@apply md:col-span-2}.btn-primary{@apply rounded bg-blue-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50}.btn-success{@apply rounded bg-green-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50}.btn-danger{@apply rounded bg-red-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50}.btn-muted{@apply rounded bg-gray-200 px-3 py-2 text-sm font-semibold}</style>
