<template>
    <AppLayout><div class="container mx-auto px-4 py-8"><h1 class="mb-8 text-3xl font-bold">Mis pedidos</h1><div class="grid gap-8 md:grid-cols-[16rem_1fr]"><aside class="h-fit rounded-lg bg-white shadow"><router-link to="/profile" class="block px-6 py-4 hover:bg-slate-50">Información personal</router-link><router-link to="/orders" class="block border-l-4 border-blue-600 bg-blue-50 px-6 py-4 font-bold text-blue-700">Mis pedidos</router-link><button class="w-full px-6 py-4 text-left text-red-600 hover:bg-red-50" @click="authStore.logout(); router.push('/login')">Cerrar sesión</button></aside><main class="space-y-5"><div v-if="loading" class="py-10 text-center">Cargando pedidos…</div><div v-else-if="error" class="rounded-lg bg-white p-8 text-center text-red-700 shadow">{{ error }} <button class="font-bold underline" @click="fetchOrders">Reintentar</button></div><div v-else-if="!orders.length" class="rounded-lg bg-white p-8 text-center text-slate-500 shadow">Aún no tienes pedidos.</div>
        <article v-for="order in orders" :key="order.id" class="overflow-hidden rounded-lg border bg-white shadow"><header class="flex items-center justify-between border-b bg-slate-50 px-5 py-4"><div><b>Pedido #{{ order.id }}</b><p class="text-sm text-slate-500">{{ formatDate(order.created_at) }}</p></div><span class="rounded-full bg-blue-100 px-3 py-1 text-xs font-bold text-blue-700">{{ statusLabel(order) }}</span></header><div class="p-5"><div v-if="order.delivery_type === 'pickup'" class="mb-4 rounded-lg bg-blue-50 p-3 text-sm"><b>Recojo en sede · {{ order.pickup_branch_name_snapshot || 'Información histórica no disponible' }}</b><p>{{ order.pickup_address_snapshot }}<template v-if="order.pickup_district_snapshot"> — {{ order.pickup_district_snapshot }}</template></p><p v-if="order.pickup_deadline_at">Fecha límite: {{ formatDate(order.pickup_deadline_at) }} · {{ deadlineLabel(order.pickup_deadline_status) }}</p></div><div v-else class="mb-4 rounded-lg bg-slate-50 p-3 text-sm"><b>Envío a domicilio · {{ order.shipping_district_snapshot || order.shipping_info?.district || 'Dirección histórica' }}</b><p>{{ order.shipping_info?.address }}</p><p>{{ order.shipping_zone_name_snapshot || 'Configuración histórica' }} · Envío S/ {{ order.shipping_amount || '0.00' }}</p></div><div v-for="item in order.items" :key="item.id" class="flex justify-between py-2"><span>{{ item.quantity }}× {{ item.product?.name || 'Producto' }}</span><b>S/ {{ item.subtotal }}</b></div><footer class="mt-3 flex items-end justify-between border-t pt-4"><router-link :to="`/orders/${order.id}/tracking`" class="font-bold text-blue-600"><i class="pi pi-map-marker mr-2"></i>Ver seguimiento</router-link><div class="text-right"><span class="block text-xs text-slate-500">Envío S/ {{ order.shipping_amount || '0.00' }} · Total</span><b class="text-xl text-blue-600">S/ {{ order.total }}</b></div></footer></div></article>
    </main></div></div></AppLayout>
</template>
<script setup>
import { onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import AppLayout from '@/layouts/AppLayout.vue';
import { useAuthStore } from '@/stores/auth';
import api from '@/api';
const authStore = useAuthStore(), router = useRouter(), orders = ref([]), loading = ref(true), error = ref('');
const formatDate = value => value ? new Date(value).toLocaleString('es-PE') : '—';
const deadlineLabel = status => ({ preparing: 'En preparación', within_deadline: 'Dentro del plazo', expired: 'Recojo vencido', picked_up: 'Recogido' }[status] || '');
const statusLabel = order => order.delivery_type === 'pickup' ? ({ ready_for_pickup: 'Listo para recoger', picked_up: 'Recogido', processing: 'En preparación', pending: 'Pendiente', confirmed: 'Confirmado', canceled: 'Cancelado' }[order.tracking_status] || order.tracking_status) : order.status;
async function fetchOrders() { loading.value = true; error.value = ''; try { orders.value = (await api.get('/orders')).data; } catch { error.value = 'No se pudieron cargar tus pedidos.'; } finally { loading.value = false; } }
onMounted(() => authStore.isAuthenticated ? fetchOrders() : router.push('/login'));
</script>
